spring:
  application:
    name: recruitment-service

server:
  port: 8080
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sql@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always  # Show detailed health check information
  metrics:
    enable:
      process: true  # Enable process-related metrics like uptime
  health:
    db:
      enabled: true  # Enable database health check
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.fasterxml.jackson: DEBUG
    org.springframework.web: DEBUG

---
spring:
  cache:
    cache-names: EMPLOYER, EMPLOYERS, JOB, JOBS, SEEKER, SEEKERS, RESUME, RESUMES, METRICS, JOB_SEEKERS
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123
    mongodb:
      host: "localhost"
      port: 27017
      username: "user" # use have to create this user
      password: "User123"
      database: "sample_db"
#      uri: "mongodb://localhost:27017/sample_db"
---
reqres:
  url: https://reqres.in
---
sentry:
  dsn: https://b37e292796c0b56c30af63c0fa6a2482@o4508170945691648.ingest.us.sentry.io/4508171026694144